name: Ergo Delta CI

on:
  push:
    tags:
      - '*'

jobs:
  build-publish:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Package
        run: make package VERSION=${{  github.ref_name }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/ergo-delta.deltaskin
